disabled_rules:
  - nesting
  - function_parameter_count
  - trailing_whitespace
  - type_name
  - function_body_length
  - identifier_name

opt_in_rules:
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma

excluded:
  - Pods
  - safeline/Core
  - safelineTests

analyzer_rules:
  - unused_import
  - unused_private_declaration

line_length:
  - 200 # warning
  - 300 # error
